using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FinalProject.Migrations
{
    /// <inheritdoc />
    public partial class SkillTableAndRelationRelationWithUser : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Skills",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Skills", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "UserSkill",
                columns: table => new
                {
                    UserId = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    SkillId = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UserSkill", x => new { x.UserId, x.SkillId });
                    table.ForeignKey(
                        name: "FK_UserSkill_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.NoAction);
                    table.ForeignKey(
                        name: "FK_UserSkill_Skills_SkillId",
                        column: x => x.SkillId,
                        principalTable: "Skills",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.NoAction);
                });

            migrationBuilder.CreateIndex(
                name: "IX_UserSkill_SkillId",
                table: "UserSkill",
                column: "SkillId");
            migrationBuilder.InsertData(
    table: "Skills",
    column: "Name",
    values: new object[]
    {
        "Ability to adjust",
        "Accessibility Design",
        "Accommodating change",
        "Accountability",
        "Active engagement",
        "Active listening",
        "Ada",
        "Adaptability",
        "Adaptation to technology",
        "Adapting in real-time to audience needs",
        "Adapting negotiation strategies",
        "Adjusting behavior to establish rapport",
        "Adobe Creative Suite ",
        "Adobe Photoshop",
        "Adobe XD",
        "AGILE",
        "Agility",
        "AI",
        "Amazon Web Services",
        "Analytical skills",
        "Android testing",
        "API integration",
        "APIs",
        "Articulating ideas",
        "Assembly language",
        "Assertiveness",
        "Attention to detail",
        "Audience engagement",
        "AWS",
        "AWS Lambda",
        "Azure Functions",
        "Bash",
        "Blog writing",
        "Brainstorming",
        "Building positive relationships",
        "C",
        "C#",
        "C++",
        "Capital Budgeting",
        "Change Management",
        "Clarity",
        "Classic Visual Basic",
        "Clear communication",
        "Cloud",
        "Cloud Infrastructure",
        "Coaching",
        "COBOL",
        "Coding",
        "Collaboration",
        "Color Theory",
        "Communication",
        "Compassion",
        "Compromise",
        "COMPUTER SCIENCE",
        "Confidence",
        "Conflict resolution",
        "Constructive feedback",
        "Constructively addressing conflicts",
        "Containerization",
        "Content Marketing",
        "Conversion Rate Optimization (CRO)",
        "Conveying information",
        "Cooperation",
        "Corporate Finance",
        "Cost Analysis",
        "Cost Management",
        "Creative ",
        "Creative thinking",
        "Creativity",
        "Critical analysis",
        "Critical reading",
        "Critical thinking",
        "Css",
        "Cultural awareness",
        "Cultural sensitivity",
        "Curiosity",
        "Custom graphics",
        "Dart",
        "Data Analysis",
        "Data assessment",
        "Data Structures and Algorithms",
        "Data visualization tools",
        "Data-based decision-making",
        "Database Administration",
        "Database Management",
        "Debugging",
        "Decision-making",
        "Deep Learning Architecture",
        "Delegation",
        "Delphi/Object Pascal",
        "Developing effective solutions",
        "Digital Forensics",
        "Diplomacy",
        "Django",
        "Docker",
        "Documentation",
        "Dot Net",
        "Effective Communication",
        "Embracing diverse viewpoints",
        "Emotional intelligence",
        "Empathy",
        "Empowerment",
        "ENGINEERING",
        "Entrepreneurial mindset",
        "Evaluating potential outcomes",
        "Evaluating risks",
        "Evaluation",
        "Evidence-based reasoning",
        "Excel",
        "Exploring alternative solutions",
        "F#",
        "Figma",
        "Financial Forecasting",
        "Financial Modeling",
        "Financial modeling software",
        "Financial Ratio Analysis",
        "Financial Statement Analysis",
        "Finding innovative solutions",
        "Finding win-win outcomes",
        "Firewalls",
        "Flask",
        "Flexibility",
        "Fortran",
        "Fostering a culture of growth",
        "Fostering a sense of ownership and confidence",
        "Fostering credibility",
        "FPGA ",
        "Frameworks",
        "GCP",
        "Git ",
        "GITHUB",
        "Go",
        "Goal setting",
        "Google Ads",
        "Google Analytics",
        "Google Cloud Platform",
        "Grammar",
        "Growth mindset",
        "Handling challenges",
        "Handling criticism",
        "Haskell",
        "Honesty",
        "HTML",
        "IBM Cloud",
        "Identifying patterns",
        "Identifying the root cause of the problem",
        "Illustration",
        "Illustrator",
        "Image Editing and Retouching",
        "Implementing navigation",
        "Incident Response",
        "InDesign",
        "Influence",
        "Influencer Marketing",
        "Information",
        "Information Design",
        "Information evaluation",
        "Initiative",
        "Inspiration",
        "Integrity",
        "Interaction Design",
        "Interpersonal Communication",
        "Interpersonal skills",
        "Intrusion detection systems (IDS) and Intrusion prevention systems (IPS)",
        "Investment Analysis",
        "InVision",
        "J#",
        "Java",
        "JavaScript",
        "jQuery",
        "Julia",
        "Kotlin",
        "Kubernetes",
        "Language Teaching",
        "Language Technology Tools",
        "Layout Design",
        "Leadership",
        "Learning agility",
        "Lisp",
        "Logical and rational thinking processes",
        "Logo",
        "Lua",
        "Machine Learning",
        "Machine Learning Algorithms",
        "Maintaining composure",
        "Managing conflict",
        "Managing resources",
        "Marketing Automation",
        "MATLAB",
        "Mediation",
        "Mentoring",
        "Microcontroller Programming",
        "Microsoft Azure",
        "Mixpanel",
        "Multitasking",
        "Mutual understanding",
        "MYSQL",
        "Natural Language Processing (NLP)",
        "Navigating challenges and change",
        "Negotiation",
        "Net",
        "Network protocols",
        "Network Security",
        "Networking",
        "Niche Language Knowledge",
        "Nonverbal communication",
        "Objective-C",
        "Objectivity",
        "OOD",
        "Open to new ideas",
        "Open-minded",
        "Open-mindedness",
        "OpenAI Gym",
        "OpenCV",
        "Organization",
        "Patience",
        "Penetration Testing",
        "Perl",
        "Perseverance",
        "Persistence",
        "Personal and professional development",
        "Persuasion",
        "PHP",
        "PL/SQL",
        "Power BI",
        "Powershell",
        "Preparation",
        "Presentation",
        "Print Design",
        "Prioritization",
        "Proactivity",
        "Problem analysis",
        "Problem-solving",
        "PROGRAMMING",
        "Project Budgeting",
        "Project charters",
        "Project Closure and Evaluation",
        "Project Documentation",
        "Project Management",
        "Project Planning and Scheduling",
        "Prolog",
        "Promoting teamwork",
        "Prototyping",
        "Providing feedback",
        "Public speaking",
        "Python",
        "PyTorch",
        "R",
        "Real-Time Operating Systems",
        "Reasoning",
        "Record-keeping",
        "Reflection",
        "Relationship building",
        "Reliability",
        "Research",
        "Resilience",
        "Resourcefulness",
        "Respect",
        "Respectful communication",
        "Responsive Design",
        "RESTful Services",
        "Risk Analysis",
        "Risk Management",
        "RLlib",
        "RTOS",
        "Ruby",
        "Ruby on Rails",
        "Rust",
        "SAS",
        "Scala",
        "Scratch",
        "Search Engine Marketing",
        "Search Engine Optimization",
        "Security",
        "Seeking opportunities for growth",
        "Self-confidence",
        "Self-motivation",
        "Self-reflection",
        "SEM",
        "SEO",
        "Serverless Computing",
        "Sharing responsibilities",
        "Sketch",
        "Slide decks",
        "Social Media Marketing",
        "SOFTWARE DEVELOPMENT",
        "Sql",
        "Stable Baselines",
        "Stakeholder communication plans",
        "Stakeholder management",
        "Statistical Analysis",
        "Statistical analysis software",
        "Stepping out of comfort zone",
        "Storytelling",
        "Strategizing",
        "Strong desire to explore",
        "Strong stage presence",
        "Surveys and Questionnaires",
        "Swift",
        "Syntax",
        "Systematic thinking",
        "Tableau",
        "Taking calculated risks",
        "Taking responsibility",
        "Task delegation",
        "Task prioritization",
        "Teamwork",
        "TensorFlow",
        "Testing",
        "Thriving in diverse environments",
        "Time management",
        "Transact SQL",
        "Translation",
        "Transparency",
        "Trust building",
        "Trustworthiness",
        "Typography",
        "Unconventional thinking",
        "Understanding",
        "Understanding different perspectives",
        "Usability Testing",
        "User Experience (UX) Optimization",
        "User Interface (UI) Design",
        "User Interviews",
        "Valuation Techniques",
        "Valuing contributions",
        "Valuing diverse perspectives",
        "Verbal communication",
        "Versatility",
        "Virtual private networks (VPNs)",
        "Vision",
        "Visual and verbal communication alignment",
        "Visual Basic .NET",
        "Visual brand identities",
        "Visual design",
        "VisualFoxPro",
        "Vocabulary Building",
        "Vulnerability Assessment",
        "Web Design",
        "Wireframing",
        "Work ethics",
        "Workflow optimization",
        "Writing Skills",
        "Written communication"
    });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "UserSkill");

            migrationBuilder.DropTable(
                name: "Skills");
        }
    }
}
